### ISSUE TITLE
"Elektronische Karte": missing osm attribution

### ISSUE THREAD

**Issue by tyrasd** [simon04/tyrolean-map#2]
As far as I can tell, the two *"Elektronische Karte"* layers are also using OSM data (at least outside of the borders of North&East Tyrol. But I don't see the required attribution on your map.

(The attribution is also missing/wrong on https://www.tirol.gv.at/data/datenkatalog/geographie-und-planung/elektronische-karte-tirol/, but that's another issue, I guess. Do you know who to contact to fix that one?)

**Comment by simon04** [comment]
I also contacted tirol.gv.at for clarification in their data catalog.
