### ISSUE TITLE
Image_2019 funktioniert nicht mehr

### ISSUE THREAD

**Issue by MarkusGaugg** [simon04/tyrolean-map#9]
Seitdem das neue Tiris 2023 Orthofoto eingespielt wurde, funktioniert das Tyrolean Map Image_2019 nicht mehr.

**Comment by simon04** [comment]
Hi, danke für den Hinweis. Bei Updates ändern sich die Namen der publizierten Orthofotos immer wieder und müssen dann in tyrolean-map nachgezogen werden. 2019–2020 sollte jetzt wieder funktionieren. Grüße!

**Comment by MarkusGaugg** [comment]
Super, vielen Dank für die schnelle Behebung und die gute Arbeit 👍
